# SF Salaries Exercise 

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

** Import pandas as pd.**

In [2]:
import pandas as pd

** Read Salaries.csv as a dataframe called sal.**

In [4]:
sal = pd.read_csv("Salaries.csv")

** Check the head of the DataFrame. **

In [5]:
sal.head()

   Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

** Use the .info() method to find out how many entries there are.**

In [6]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

**What is the average BasePay ?**

In [7]:
sal['BasePay'].mean()

66325.44884050643

** What is the highest amount of OvertimePay in the dataset ? **

In [8]:
sal["OvertimePay"].max()

245131.88

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [9]:
sal[sal["EmployeeName"]=="JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [10]:
sal[sal["EmployeeName"]=="JOSEPH DRISCOLL"]["TotalPayBenefits"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

** What is the name of highest paid person (including benefits)?**

In [11]:
x = sal["TotalPayBenefits"].max()
sal[sal["TotalPayBenefits"]==x]

   Id    EmployeeName  ...         Agency  Status
0   1  NATHANIEL FORD  ...  San Francisco     NaN

[1 rows x 13 columns]

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [12]:
y = sal["TotalPayBenefits"].min()
sal[sal["TotalPayBenefits"]==y]

            Id EmployeeName  ...         Agency  Status
148653  148654    Joe Lopez  ...  San Francisco     NaN

[1 rows x 13 columns]

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [13]:
sal.groupby("Year").mean()["BasePay"]

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

** How many unique job titles are there? **

In [14]:
len(sal["JobTitle"].unique())

2159

** What are the top 5 most common jobs? **

In [15]:
sal['JobTitle'].value_counts().head(5)

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

In [16]:
sal[sal["Year"]==2013]["JobTitle"].value_counts()

Transit Operator                2295
Special Nurse                   1445
Registered Nurse                1231
Public Svc Aide-Public Works     859
Custodian                        789
                                ...
Sr Opers Mgr                       1
Senior Plan Checker                1
Attorney, Tax Collector            1
Statistician                       1
Electroencephalograph Tech 1       1
Name: JobTitle, Length: 1051, dtype: int64

** How many people have the word Chief in their job title? (This is pretty tricky) **

In [29]:
strlist = ["chief"]
count=0
for x in sal['JobTitle']:
  for sub in strlist:
    if sub in x.lower():
      count=count+1
count

627

** Bonus: Is there a correlation between length of the Job Title string and Salary? **

In [59]:
ls = []
for x in sal["JobTitle"]:
  ls.append(len(x))
ls
new = pd.concat([pd.Series(ls), sal["TotalPayBenefits"]],axis=1)
new.rename(columns = {0:'title_len'}, inplace = True)
print(new.corr())

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

# Great Job!